#!/bin/zsh

#install brew before yadr to avoid slowdown
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#install yadr
sh -c "`curl -fsSL https://raw.githubusercontent.com/skwp/dotfiles/master/install.sh`"

#install atom
brew cask install atom

#install spectacle
brew cask install spectacle

#install chrome
brew cask install google-chrome

#install python
brew install python
brew install python@2
pip install --upgrade setuptools
pip install --upgrade pip


#install docker
brew cask install docker
#run docker app

# zsh auto
brew info zsh-autosuggestions
brew install zsh-autosuggestions

# remove python2 
# make a reference to python3 like this.
ln -s /usr/local/bin/python3 /usr/local/bin/python   
